services:
  web_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REQUIREMENTS: requirements/development.txt
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      ENVIRONMENT: ${SECRET_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db_postgres
    depends_on:
      - db_production
    networks:
      - app-network

  db_production:
    image: postgres:17-alpine
    container_name: db_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
